/**
 * Map Google Business Profile primary-category strings to our 46
 * ReviewCategory buckets. Used at location creation to auto-classify
 * a newly connected location into the right preset.
 *
 * Strategy:
 *   1. Direct exact-match lookup against the table below (case-insensitive).
 *   2. Substring/fuzzy match: for unknown strings, scan for a keyword
 *      hint ("dental", "yoga", "tax", "translat", "noodle", "hotel", …).
 *   3. Fallback: 'other'.
 *
 * The table covers Google's most common ~250 categories that local
 * businesses identify as. We don't try to be exhaustive — anything
 * that doesn't match falls through to 'other' and the admin can pick
 * from the dropdown in location settings.
 */

import type { ReviewCategory } from "./industry-presets";

const DIRECT_MAP: Record<string, ReviewCategory> = {
  // ===== Food & Beverage — Restaurant =====
  "Restaurant": "restaurant",
  "American restaurant": "restaurant",
  "Italian restaurant": "restaurant",
  "Chinese restaurant": "restaurant",
  "Japanese restaurant": "restaurant",
  "Korean restaurant": "restaurant",
  "Mexican restaurant": "restaurant",
  "Vietnamese restaurant": "restaurant",
  "Thai restaurant": "restaurant",
  "Indian restaurant": "restaurant",
  "Mediterranean restaurant": "restaurant",
  "French restaurant": "restaurant",
  "Spanish restaurant": "restaurant",
  "Greek restaurant": "restaurant",
  "Seafood restaurant": "restaurant",
  "Steak house": "restaurant",
  "Sushi restaurant": "restaurant",
  "Ramen restaurant": "restaurant",
  "Dim sum restaurant": "restaurant",
  "Hot pot restaurant": "restaurant",
  "Hotpot restaurant": "restaurant",
  "Buffet restaurant": "restaurant",
  "Family restaurant": "restaurant",
  "Fast food restaurant": "restaurant",
  "Pizza restaurant": "restaurant",
  "Burger restaurant": "restaurant",
  "BBQ restaurant": "restaurant",
  "Barbecue restaurant": "restaurant",
  "Vegetarian restaurant": "restaurant",
  "Vegan restaurant": "restaurant",
  "Asian restaurant": "restaurant",
  "Latin American restaurant": "restaurant",
  "Caribbean restaurant": "restaurant",
  "Middle Eastern restaurant": "restaurant",
  "Brazilian restaurant": "restaurant",
  "Halal restaurant": "restaurant",
  "Kosher restaurant": "restaurant",
  "Diner": "restaurant",
  "Bistro": "restaurant",
  "Brewpub": "restaurant",
  // Cafe / Bakery
  "Cafe": "cafe_bakery",
  "Coffee shop": "cafe_bakery",
  "Coffee store": "cafe_bakery",
  "Espresso bar": "cafe_bakery",
  "Bakery": "cafe_bakery",
  "Pastry shop": "cafe_bakery",
  "Cake shop": "cafe_bakery",
  "Dessert shop": "cafe_bakery",
  "Ice cream shop": "cafe_bakery",
  "Frozen yogurt shop": "cafe_bakery",
  "Bubble tea store": "cafe_bakery",
  "Tea house": "cafe_bakery",
  "Tea shop": "cafe_bakery",
  "Donut shop": "cafe_bakery",
  // Bar / Lounge
  "Bar": "bar_lounge",
  "Cocktail bar": "bar_lounge",
  "Sports bar": "bar_lounge",
  "Wine bar": "bar_lounge",
  "Pub": "bar_lounge",
  "Brewery": "bar_lounge",
  "Beer garden": "bar_lounge",
  "Karaoke bar": "bar_lounge",
  "Lounge": "bar_lounge",
  "Night club": "bar_lounge",
  "Nightclub": "bar_lounge",
  // Takeout / Delivery
  "Food truck": "takeout_delivery",
  "Takeout restaurant": "takeout_delivery",
  "Delivery restaurant": "takeout_delivery",
  "Meal delivery": "takeout_delivery",
  "Caterer": "takeout_delivery",
  "Catering service": "takeout_delivery",

  // ===== Medical & Health =====
  "Dentist": "dental",
  "Dental clinic": "dental",
  "Cosmetic dentist": "dental",
  "Pediatric dentist": "dental",
  "Orthodontist": "dental",
  "Periodontist": "dental",
  "Endodontist": "dental",
  "Oral surgeon": "dental",
  "Dental implants periodontist": "dental",
  "Dental hygienist": "dental",
  "Acupuncturist": "acupuncture_tcm",
  "Acupuncture clinic": "acupuncture_tcm",
  "Chinese medicine clinic": "acupuncture_tcm",
  "Chinese medicine practitioner": "acupuncture_tcm",
  "Traditional Chinese medicine clinic": "acupuncture_tcm",
  "Herbalist": "acupuncture_tcm",
  "Herbal medicine store": "acupuncture_tcm",
  "Chiropractor": "chiropractic",
  "Chiropractic clinic": "chiropractic",
  "Optometrist": "optometry",
  "Eye care center": "optometry",
  "Ophthalmologist": "optometry",
  "Optician": "optometry",
  "Physical therapist": "physical_therapy",
  "Physical therapy clinic": "physical_therapy",
  "Rehabilitation center": "physical_therapy",
  "Sports medicine clinic": "physical_therapy",
  "Sports medicine physician": "physical_therapy",
  "Occupational therapist": "physical_therapy",
  "Psychologist": "mental_health",
  "Psychiatrist": "mental_health",
  "Therapist": "mental_health",
  "Mental health clinic": "mental_health",
  "Counselor": "mental_health",
  "Family counselor": "mental_health",
  "Marriage counselor": "mental_health",
  "Veterinarian": "veterinary",
  "Veterinary care": "veterinary",
  "Animal hospital": "veterinary",
  "Pet hospital": "veterinary",
  "Pet groomer": "veterinary",
  "Pet boarding service": "veterinary",
  "General practitioner": "medical_general",
  "Family practice physician": "medical_general",
  "Internist": "medical_general",
  "Pediatrician": "medical_general",
  "Medical clinic": "medical_general",
  "Urgent care center": "medical_general",
  "Walk-in clinic": "medical_general",
  "Medical group": "medical_general",
  "Cardiologist": "medical_general",
  "OB-GYN": "medical_general",
  "Obstetrician-gynecologist": "medical_general",
  "Pain management physician": "medical_general",
  "Dermatologist": "medspa_aesthetic",
  "Medical spa": "medspa_aesthetic",
  "Aesthetic medicine doctor": "medspa_aesthetic",
  "Cosmetic surgeon": "medspa_aesthetic",
  "Plastic surgeon": "medspa_aesthetic",
  "Laser hair removal service": "medspa_aesthetic",
  "Weight loss service": "medspa_aesthetic",
  "Skin care clinic": "medspa_aesthetic",

  // ===== Attorney =====
  "Immigration attorney": "attorney_immigration",
  "Immigration lawyer": "attorney_immigration",
  "Estate planning attorney": "attorney_estate_family",
  "Family law attorney": "attorney_estate_family",
  "Divorce lawyer": "attorney_estate_family",
  "Probate lawyer": "attorney_estate_family",
  "Business attorney": "attorney_business_tax",
  "Tax attorney": "attorney_business_tax",
  "Corporate lawyer": "attorney_business_tax",
  "Personal injury attorney": "attorney_personal_injury",
  "Personal injury lawyer": "attorney_personal_injury",
  "Trial attorney": "attorney_personal_injury",
  "Attorney": "attorney_general",
  "Law firm": "attorney_general",
  "Lawyer": "attorney_general",
  "Criminal justice attorney": "attorney_general",
  "Criminal defense attorney": "attorney_general",
  "Notary public": "translation_immigration",

  // ===== Real Estate & Insurance =====
  "Real estate agent": "real_estate",
  "Real estate agency": "real_estate",
  "Real estate broker": "real_estate",
  "Property management company": "real_estate",
  "Real estate appraiser": "real_estate",
  "Real estate consultant": "real_estate",
  "Apartment rental agency": "real_estate",
  "Insurance agency": "insurance",
  "Insurance company": "insurance",
  "Auto insurance agency": "insurance",
  "Home insurance agency": "insurance",
  "Life insurance agency": "insurance",
  "Health insurance agency": "insurance",
  "Insurance broker": "insurance",
  "Mortgage broker": "mortgage_loan",
  "Mortgage lender": "mortgage_loan",
  "Loan agency": "mortgage_loan",

  // ===== Auto =====
  "Auto repair shop": "auto_repair",
  "Mechanic": "auto_repair",
  "Auto body shop": "auto_repair",
  "Brake shop": "auto_repair",
  "Tire shop": "auto_repair",
  "Oil change service": "auto_repair",
  "Transmission shop": "auto_repair",
  "Auto tune up service": "auto_repair",
  "Car repair and maintenance service": "auto_repair",
  "Auto electrical service": "auto_repair",
  "Car dealer": "auto_sales",
  "Used car dealer": "auto_sales",
  "Auto dealer": "auto_sales",
  "Auto broker": "auto_sales",
  "Motor vehicle dealer": "auto_sales",
  "Auto detailing service": "auto_detailing",
  "Car wash": "auto_detailing",
  "Window tinting service": "auto_detailing",

  // ===== Travel =====
  "Hotel": "hotel_lodging",
  "Motel": "hotel_lodging",
  "Resort hotel": "hotel_lodging",
  "Inn": "hotel_lodging",
  "Bed & breakfast": "hotel_lodging",
  "Boutique hotel": "hotel_lodging",
  "Extended stay hotel": "hotel_lodging",
  "Vacation rental agency": "hotel_lodging",
  "Travel agency": "travel_agency",
  "Tour operator": "travel_agency",
  "Tour agency": "travel_agency",
  "Cruise line company": "travel_agency",

  // ===== Health Food & Products =====
  "Vitamin & supplements store": "health_supplements",
  "Health food store": "health_supplements",
  "Nutritionist": "health_supplements",
  "Asian grocery store": "specialty_grocery",
  "Asian food store": "specialty_grocery",
  "Chinese supermarket": "specialty_grocery",
  "Korean grocery store": "specialty_grocery",
  "Japanese grocery store": "specialty_grocery",
  "Indian grocery store": "specialty_grocery",
  "Mexican grocery store": "specialty_grocery",
  "Latin grocery store": "specialty_grocery",
  "International grocery store": "specialty_grocery",
  "Halal market": "specialty_grocery",
  "Kosher grocery store": "specialty_grocery",
  "Organic food store": "specialty_grocery",
  "Specialty grocery store": "specialty_grocery",
  "Gourmet grocery store": "specialty_grocery",

  // ===== Home Services =====
  "HVAC contractor": "home_repair",
  "Air conditioning contractor": "home_repair",
  "Heating contractor": "home_repair",
  "Plumber": "home_repair",
  "Plumbing supply store": "home_repair",
  "Electrician": "home_repair",
  "Handyman": "home_repair",
  "Appliance repair service": "home_repair",
  "Painter": "home_repair",
  "Drywall contractor": "home_repair",
  "Carpenter": "home_repair",
  "Roofing contractor": "home_repair",
  "Flooring contractor": "home_repair",
  "House cleaning service": "cleaning_service",
  "Cleaning service": "cleaning_service",
  "Commercial cleaning service": "cleaning_service",
  "Carpet cleaning service": "cleaning_service",
  "Maid service": "cleaning_service",
  "Window cleaning service": "cleaning_service",
  "Landscaper": "landscape_pest",
  "Lawn care service": "landscape_pest",
  "Garden center": "landscape_pest",
  "Tree service": "landscape_pest",
  "Pest control service": "landscape_pest",
  "Termite control service": "landscape_pest",
  "Snow removal service": "landscape_pest",
  "Mover": "moving_storage",
  "Moving company": "moving_storage",
  "Movers": "moving_storage",
  "Self-storage facility": "moving_storage",
  "Storage facility": "moving_storage",

  // ===== Beauty & Fitness =====
  "Hair salon": "hair_salon",
  "Beauty salon": "hair_salon",
  "Barber shop": "hair_salon",
  "Barbershop": "hair_salon",
  "Hairdresser": "hair_salon",
  "Hair stylist": "hair_salon",
  "Hair extensions service": "hair_salon",
  "Nail salon": "nail_salon",
  "Nail care": "nail_salon",
  "Manicurist": "nail_salon",
  "Eyebrow bar": "nail_salon",
  "Waxing hair removal service": "nail_salon",
  "Day spa": "spa_massage",
  "Spa": "spa_massage",
  "Massage therapist": "spa_massage",
  "Massage spa": "spa_massage",
  "Foot massage parlor": "spa_massage",
  "Reflexologist": "spa_massage",
  "Facial spa": "spa_massage",
  "Gym": "gym_fitness",
  "Fitness center": "gym_fitness",
  "Personal trainer": "gym_fitness",
  "Yoga studio": "gym_fitness",
  "Pilates studio": "gym_fitness",
  "Dance school": "gym_fitness",
  "Boxing gym": "gym_fitness",
  "CrossFit gym": "gym_fitness",
  "Martial arts school": "gym_fitness",

  // ===== Apparel & Retail =====
  "Clothing store": "apparel_clothing",
  "Women's clothing store": "apparel_clothing",
  "Men's clothing store": "apparel_clothing",
  "Children's clothing store": "apparel_clothing",
  "Boutique": "apparel_clothing",
  "Tailor": "apparel_clothing",
  "Bridal shop": "apparel_clothing",
  "Jewelry store": "jewelry_watch",
  "Watch store": "jewelry_watch",
  "Watch repair service": "jewelry_watch",
  "Jeweler": "jewelry_watch",
  "Diamond dealer": "jewelry_watch",
  "Shoe store": "shoes_accessories",
  "Leather goods store": "shoes_accessories",
  "Handbag store": "shoes_accessories",
  "Sunglasses store": "shoes_accessories",
  "Hat shop": "shoes_accessories",
  "Eyewear store": "shoes_accessories",

  // ===== Education / Tutoring =====
  "Tutoring service": "tutoring_test_prep",
  "Tutor": "tutoring_test_prep",
  "Test preparation center": "tutoring_test_prep",
  "After-school program": "tutoring_test_prep",
  "Educational consultant": "tutoring_test_prep",
  "College preparatory school": "tutoring_test_prep",
  "Language school": "language_school",
  "English language school": "language_school",
  "Chinese language school": "language_school",
  "Spanish language school": "language_school",
  "Translator": "translation_immigration",
  "Translation agency": "translation_immigration",
  "Translation service": "translation_immigration",
  "Interpreter": "translation_immigration",
  "Immigration & naturalization service": "translation_immigration",

  // ===== Professional Services =====
  "Accountant": "accounting_tax",
  "Accounting firm": "accounting_tax",
  "Tax preparation service": "accounting_tax",
  "Tax consultant": "accounting_tax",
  "Certified public accountant": "accounting_tax",
  "Bookkeeping service": "accounting_tax",
  "Financial planner": "financial_advisor",
  "Financial consultant": "financial_advisor",
  "Investment service": "financial_advisor",
  "Wealth management service": "financial_advisor",
  "Photographer": "professional_general",
  "Wedding photographer": "professional_general",
  "Portrait photographer": "professional_general",
  "Photography studio": "professional_general",
  "Graphic designer": "professional_general",
  "Marketing agency": "professional_general",
  "Marketing consultant": "professional_general",
  "Advertising agency": "professional_general",
  "Web designer": "professional_general",
  "Website designer": "professional_general",
  "Printing service": "professional_general",
  "Print shop": "professional_general",
  "Business management consultant": "professional_general",
  "Consultant": "professional_general",
};

/**
 * Lower-cased keyword hints scanned when DIRECT_MAP misses. Order matters
 * — first match wins, so put more specific tokens before generic ones.
 */
const FUZZY_HINTS: Array<[string, ReviewCategory]> = [
  // Medical/health (specific first)
  ["acupunc", "acupuncture_tcm"],
  ["chinese medicine", "acupuncture_tcm"],
  ["herbal", "acupuncture_tcm"],
  ["dental", "dental"],
  ["dentist", "dental"],
  ["orthodont", "dental"],
  ["chiroprac", "chiropractic"],
  ["optomet", "optometry"],
  ["eye care", "optometry"],
  ["physical therap", "physical_therapy"],
  ["sports medicine", "physical_therapy"],
  ["psycholog", "mental_health"],
  ["psychiatr", "mental_health"],
  ["counsel", "mental_health"],
  ["mental health", "mental_health"],
  ["therapist", "mental_health"],
  ["veterin", "veterinary"],
  ["animal hospital", "veterinary"],
  ["medspa", "medspa_aesthetic"],
  ["med spa", "medspa_aesthetic"],
  ["dermat", "medspa_aesthetic"],
  ["aestheti", "medspa_aesthetic"],
  ["plastic surg", "medspa_aesthetic"],
  ["weight loss", "medspa_aesthetic"],
  // Catchall medical
  ["clinic", "medical_general"],
  ["physician", "medical_general"],
  ["doctor", "medical_general"],
  ["urgent care", "medical_general"],

  // Legal
  ["immigration", "translation_immigration"], // when the business is translation/immigration; immigration attorney is caught first via DIRECT_MAP
  ["attorney", "attorney_general"],
  ["lawyer", "attorney_general"],
  ["law firm", "attorney_general"],

  // Real estate / insurance / loan
  ["real estate", "real_estate"],
  ["property management", "real_estate"],
  ["insurance", "insurance"],
  ["mortgage", "mortgage_loan"],
  ["loan", "mortgage_loan"],

  // Auto
  ["car wash", "auto_detailing"],
  ["detailing", "auto_detailing"],
  ["window tint", "auto_detailing"],
  ["auto repair", "auto_repair"],
  ["mechanic", "auto_repair"],
  ["body shop", "auto_repair"],
  ["tire", "auto_repair"],
  ["car dealer", "auto_sales"],
  ["dealership", "auto_sales"],

  // Travel
  ["hotel", "hotel_lodging"],
  ["motel", "hotel_lodging"],
  ["resort", "hotel_lodging"],
  ["lodging", "hotel_lodging"],
  ["travel agency", "travel_agency"],
  ["tour operator", "travel_agency"],
  ["cruise", "travel_agency"],

  // Health food / grocery
  ["supplement", "health_supplements"],
  ["vitamin", "health_supplements"],
  ["health food", "health_supplements"],
  ["asian grocery", "specialty_grocery"],
  ["specialty grocery", "specialty_grocery"],

  // Home services
  ["hvac", "home_repair"],
  ["plumb", "home_repair"],
  ["electric", "home_repair"],
  ["handyman", "home_repair"],
  ["appliance repair", "home_repair"],
  ["painter", "home_repair"],
  ["roofing", "home_repair"],
  ["cleaning", "cleaning_service"],
  ["maid", "cleaning_service"],
  ["landscap", "landscape_pest"],
  ["lawn", "landscape_pest"],
  ["pest control", "landscape_pest"],
  ["tree service", "landscape_pest"],
  ["mover", "moving_storage"],
  ["moving company", "moving_storage"],
  ["storage", "moving_storage"],

  // Beauty / fitness
  ["barber", "hair_salon"],
  ["hair", "hair_salon"],
  ["nail", "nail_salon"],
  ["manicur", "nail_salon"],
  ["spa", "spa_massage"],
  ["massage", "spa_massage"],
  ["reflexolog", "spa_massage"],
  ["facial", "spa_massage"],
  ["yoga", "gym_fitness"],
  ["pilates", "gym_fitness"],
  ["gym", "gym_fitness"],
  ["fitness", "gym_fitness"],
  ["martial arts", "gym_fitness"],

  // Apparel / retail
  ["clothing", "apparel_clothing"],
  ["boutique", "apparel_clothing"],
  ["tailor", "apparel_clothing"],
  ["jewel", "jewelry_watch"],
  ["watch", "jewelry_watch"],
  ["shoe", "shoes_accessories"],
  ["handbag", "shoes_accessories"],
  ["leather goods", "shoes_accessories"],

  // Education
  ["tutor", "tutoring_test_prep"],
  ["test prep", "tutoring_test_prep"],
  ["after-school", "tutoring_test_prep"],
  ["language school", "language_school"],
  ["esl", "language_school"],
  ["translat", "translation_immigration"],
  ["interpreter", "translation_immigration"],
  ["notary", "translation_immigration"],

  // Professional
  ["accountant", "accounting_tax"],
  ["accounting", "accounting_tax"],
  ["tax prep", "accounting_tax"],
  ["bookkeep", "accounting_tax"],
  ["cpa", "accounting_tax"],
  ["financial planner", "financial_advisor"],
  ["financial advisor", "financial_advisor"],
  ["investment", "financial_advisor"],
  ["wealth management", "financial_advisor"],
  ["photograph", "professional_general"],
  ["graphic design", "professional_general"],
  ["marketing", "professional_general"],
  ["advertising", "professional_general"],
  ["web design", "professional_general"],
  ["print shop", "professional_general"],
  ["printing service", "professional_general"],

  // Food
  ["restaurant", "restaurant"],
  ["bistro", "restaurant"],
  ["diner", "restaurant"],
  ["sushi", "restaurant"],
  ["ramen", "restaurant"],
  ["noodle", "restaurant"],
  ["pizza", "restaurant"],
  ["burger", "restaurant"],
  ["bbq", "restaurant"],
  ["barbecue", "restaurant"],
  ["buffet", "restaurant"],
  ["steakhouse", "restaurant"],
  ["seafood", "restaurant"],
  ["cafe", "cafe_bakery"],
  ["coffee", "cafe_bakery"],
  ["bakery", "cafe_bakery"],
  ["pastry", "cafe_bakery"],
  ["bubble tea", "cafe_bakery"],
  ["boba", "cafe_bakery"],
  ["ice cream", "cafe_bakery"],
  ["donut", "cafe_bakery"],
  ["dessert", "cafe_bakery"],
  ["bar", "bar_lounge"],
  ["lounge", "bar_lounge"],
  ["pub", "bar_lounge"],
  ["brewery", "bar_lounge"],
  ["karaoke", "bar_lounge"],
  ["nightclub", "bar_lounge"],
  ["food truck", "takeout_delivery"],
  ["takeout", "takeout_delivery"],
  ["delivery", "takeout_delivery"],
  ["caterer", "takeout_delivery"],
  ["catering", "takeout_delivery"],
];

/**
 * Classify a Google Business Profile primary-category string into a
 * ReviewCategory bucket. Falls back to 'other' when nothing matches.
 */
export function classifyByGoogleCategory(
  googleCategory: string | null | undefined,
): ReviewCategory {
  if (!googleCategory) return "other";
  const raw = googleCategory.trim();
  if (!raw) return "other";

  // 1. Direct exact match (case-insensitive normalization).
  for (const [k, v] of Object.entries(DIRECT_MAP)) {
    if (k.toLowerCase() === raw.toLowerCase()) return v;
  }

  // 2. Fuzzy keyword hint.
  const lower = raw.toLowerCase();
  for (const [hint, cat] of FUZZY_HINTS) {
    if (lower.includes(hint)) return cat;
  }

  // 3. Nothing matched.
  return "other";
}
